name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: "0"
        token: ${{ secrets.GIT_BOT_TOKEN }}
    - uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: ${{ format('https://x-access-token:{0}@github.com/', secrets.GIT_BOT_TOKEN) }}
    - id: prep
      name: prep
      uses: docker://gcr.io/jenkinsxio/jx-release-version:1.0.46
      with:
        args: -c "echo ::set-output name=version::$(jx-release-version)"
        entrypoint: bash
    - env:
        GITHUB_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}
      name: chart-docs
      uses: docker://jnorwood/helm-docs:v1.4.0
      with:
        args: -c "if [ -d \"charts/$REPO_NAME\" ]; then cd charts/$REPO_NAME; helm-docs;
          else echo no charts; fi"
        entrypoint: /bin/ash
    - env:
        GITHUB_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}
        REPO_NAME: ${{ github.event.repository.name }}
        VERSION: ${{ steps.prep.outputs.version }}
      name: changelog
      uses: docker://gcr.io/jenkinsxio/jx-changelog:0.0.30
      with:
        entrypoint: .github/workflows/jenkins-x/changelog.sh
    - env:
        VERSION: ${{ steps.prep.outputs.version }}
        GITHUB_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}
        REPOSITORY: ${{ github.repository }}
      name: upload-binaries
      uses: docker://goreleaser/goreleaser:v0.155.0
      with:
        entrypoint: .github/workflows/jenkins-x/upload-binaries.sh
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: jenkins-x
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build and push jx-boot
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile-boot
        platforms: linux/amd64,linux/arm64
        push: true
        build-args: |
          VERSION=${{ steps.prep.outputs.version }}
        tags: |
          ghcr.io/jenkins-x/jx-boot:latest
          ghcr.io/jenkins-x/jx-boot:${{ steps.prep.outputs.version }}
    - name: Build and push jx-tfo-aws
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile-tfo-aws
        platforms: linux/amd64
        push: true
        build-args: |
          VERSION=${{ steps.prep.outputs.version }}
        tags: |
          ghcr.io/jenkins-x/terraform-operator-aws:latest
          ghcr.io/jenkins-x/terraform-operator-aws:${{ steps.prep.outputs.version }}
    - name: Build and push jx-tfo-gcp
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile-tfo-gcp
        platforms: linux/amd64
        push: true
        build-args: |
          VERSION=${{ steps.prep.outputs.version }}
        tags: |
          ghcr.io/jenkins-x/terraform-operator-gcp:latest
          ghcr.io/jenkins-x/terraform-operator-gcp:${{ steps.prep.outputs.version }}
    - name: Build and push jx-cli
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        build-args: |
          VERSION=${{ steps.prep.outputs.version }}
        tags: |
          ghcr.io/jenkins-x/jx-cli:latest
          ghcr.io/jenkins-x/jx-cli:${{ steps.prep.outputs.version }}
  release2:
    runs-on: ubuntu-latest
    needs: release
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: "0"
        token: ${{ secrets.GIT_BOT_TOKEN }}
    - id: getrelease
      name: getrelease
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: jenkins-x/jx-cli
    - id: prep
      name: prep
      env:
        VERSION: ${{ steps.getrelease.outputs.release }}
      run: |
        echo "::set-output name=version::${VERSION#v}"
    - uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: ${{ format('https://x-access-token:{0}@github.com/', secrets.GIT_BOT_TOKEN) }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: jenkins-x
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build and push jx-go
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile-go
        platforms: linux/amd64
        push: true
        build-args: |
          VERSION=${{ steps.prep.outputs.version }}
        tags: |
          ghcr.io/jenkins-x/jx-go:latest
          ghcr.io/jenkins-x/jx-go:${{ steps.prep.outputs.version }}
    - name: Build and push jx-go-maven
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile-go-maven
        platforms: linux/amd64
        push: true
        build-args: |
          VERSION=${{ steps.prep.outputs.version }}
        tags: |
          ghcr.io/jenkins-x/jx-go-maven:latest
          ghcr.io/jenkins-x/jx-go-maven:${{ steps.prep.outputs.version }}
    - env:
        GITHUB_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}
        JX_REPOSITORY_USERNAME: jenkins-x-bot-test
        VERSION: ${{ steps.prep.outputs.version }}
      name: release-chart
      uses: docker://ghcr.io/jenkins-x/jx-boot:3.1.189
      with:
        entrypoint: .github/workflows/jenkins-x/release-chart.sh
    - env:
        GIT_USERNAME: jenkins-x-bot-test
        GITHUB_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}
        VERSION: ${{ steps.prep.outputs.version}}
        XDG_CONFIG_HOME: /github/home/.config
      name: promote-release
      uses: docker://gcr.io/jenkinsxio/jx-updatebot:0.0.48
      with:
        args: pr --git-credentials
"on":
  push:
    branches:
    - main
    - master
